// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels(in *jlexer.Lexer, out *VoteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "user":
			out.User = int(in.Int())
		case "thread":
			out.Thread = int(in.Int())
		case "voice":
			out.Voice = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels(out *jwriter.Writer, in VoteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"user\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.Int(int(in.User))
	}
	{
		const prefix string = ",\"thread\":"
		out.RawString(prefix)
		out.Int(int(in.Thread))
	}
	{
		const prefix string = ",\"voice\":"
		out.RawString(prefix)
		out.Int(int(in.Voice))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VoteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VoteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VoteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VoteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels(l, v)
}
func easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels1(in *jlexer.Lexer, out *VoteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "nickname":
			out.Nickname = string(in.String())
		case "voice":
			out.Voice = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels1(out *jwriter.Writer, in VoteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nickname\":"
		out.RawString(prefix[1:])
		out.String(string(in.Nickname))
	}
	{
		const prefix string = ",\"voice\":"
		out.RawString(prefix)
		out.Int(int(in.Voice))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VoteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VoteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ecfa40EncodeExampleComGreetingsInternalAppModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VoteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VoteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ecfa40DecodeExampleComGreetingsInternalAppModels1(l, v)
}
