apiVersion: v1
kind: Pod
metadata:
  name: forum
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: forum
spec:
  containers:
    - name: forum
      image: yutfut/forum:v1
      ports:
        - containerPort: 5000