name: DevOps

on: [push]

jobs:
  test:
    name: Tests
      runs-on: ubuntu-latest
      steps:
        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: 1.17
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Install Dependecies
          run: go get ./...

        - name: Go mod tidy
          run: go mod tidy

        - name: Test
          run: go test ./...