name: DevOps

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependecies
        run: go get ./...

      - name: Go mod tidy
        run: go mod tidy

      - name: Test
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image back
        run: docker build -f=backend.Dockerfile -t yutfut/devopsback:v1 .

      - name: Push the image bcak
        run: docker push yutfut/devopsback:v1

      - name: Build Docker image back
        run: docker build -f=database.Dockerfile -t yutfut/devopsdatabase:v1 .

      - name: Push the image bcak
        run: docker push yutfut/devopsdatabase:v1